
tasks:
  - init: npm install && npm run build
    command: npm run start



vscode:
  extensions:
    - dsznajder.es7-react-js-snippets
    - whizkydee.material-palenight-theme
    - bradlc.vscode-tailwindcss
    - Prisma.prisma
