import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/css/globals.css';
import { Headers } from '@/components/headers';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          'min-h-screen bg-background text-foreground'
        )}
      >
        <Headers />
        {children}
      </body>
    </html>
  );
}
